apiVersion: v1
kind: Secret
metadata:
  annotations:
    build.knative.dev/docker-0: $registryUrl
  name: basic-user-pass
stringData:
  username: $username
  password: $password
type: kubernetes.io/basic-auth
