apiVersion: v1
kind: ConfigMap
metadata:
  name: dmn-quarkus-knative-builder-env
data:
  maven_mirror: $mavenMirror
  build_template: "build-dmn-quarkus"
  serviceAccount: "build-bot"
  registryAccount: $imageRegistry